name:  EnderdragonRespawner
main:  com.fuzzycraft.fuzzy.EnderdragonRespawner
version:  2.0.0
commands:
    er:
        description: Manage Enderdragon Respawner Events
        permission: enderdragonrespawner
        usage: |
            er [start|stop|restart] <world>
permissions:
    enderdragonrespawner:
        description: Let's a player manage any Enderdragon Respawner events
        default: op